$(function(){
	$(".ContentItem").hover(function(){
		$(this).css("border-color","#389cff")
		$(this).find(".ContentItemSpan").fadeOut();
	},function(){
		$(this).css("border-color","");
		$(this).find(".ContentItemSpan").fadeIn();
	});
});